#!/usr/bin/env python

import logging
logging.basicConfig(level=logging.DEBUG,
                    #format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                    format='%(name)-22s %(levelname)-8s %(message)s',
                    datefmt='%m-%d %H:%M')


import Sloppy
from Sloppy.Base import const
from Sloppy.Gtk import application


const.set_path(Sloppy.__path__[0])
application.main()

